/**
 * ============================================================================
 * OFFLINE-FIRST MULTI-PLATFORM ACCOUNTING SYSTEM
 * Service: Bidirectional Append-Only Sync Engine (Push / Pull Batch Worker)
 * Module:  src/services/SyncEngine.ts
 * ============================================================================
 *
 * ARCHITECTURAL SPECIFICATIONS & DISTRIBUTED SYSTEMS PATTERNS:
 * 1. Transactional Outbox Pattern (Push Pipeline):
 *    - Queries `sync_queue` for records where `sync_status = 'PENDING'`.
 *    - Atomic batching (up to 50 records) transitioned to 'SYNCING'.
 *    - Assembles an append-only JSON batch envelope.
 *    - Uploads to Google Drive v3 via multipart REST upload under `google_folder_id`.
 *    - Prunes or marks synced records on HTTP 200/201 acknowledgment.
 *    - Exponential backoff & retry counter on network or API failures.
 *
 * 2. Append-Only Pull Pipeline:
 *    - Tracks chronological high-water mark via `sync_meta` ('GLOBAL').
 *    - Queries Google Drive for files created after `last_sync_timestamp`.
 *    - Self-Origin Filtering: Ignores batches generated by the current device.
 *    - Applies idempotent upserts (`INSERT OR REPLACE INTO [table]`) inside a
 *      single atomic SQLite transaction with foreign key deferral.
 *    - Advances `last_sync_timestamp` to the latest applied batch's `createdTime`.
 *
 * 3. Reactive Orchestration & Concurrency Guard:
 *    - Sequential pipeline execution: Auth Verification -> Push -> Pull.
 *    - State machine status broadcasting: IDLE -> SYNCING_PUSH -> SYNCING_PULL -> SUCCESS / ERROR.
 *    - Background periodic worker with non-overlapping execution lock.
 */

import { SQLiteDatabase } from './NumberingService';
import {
  DriveAuthService,
  SETTINGS_KEYS,
  getSetting,
} from './DriveAuthService';

// ----------------------------------------------------------------------------
// 1. CONSTANTS & SYNC CONFIGURATION
// ----------------------------------------------------------------------------

export const SYNC_CONFIG = {
  BATCH_SIZE: 50,
  MAX_RETRIES: 5,
  UPLOAD_MULTIPART_URL: 'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',
  DRIVE_FILES_URL: 'https://www.googleapis.com/drive/v3/files',
  GLOBAL_META_ENTITY: 'GLOBAL',
  DEFAULT_EPOCH_ISO: '1970-01-01T00:00:00.000Z',
  DEFAULT_SYNC_INTERVAL_MS: 60 * 1000, // 60 seconds
  FILE_PREFIX: 'BATCH_',
} as const;

// Strict whitelist of syncable entities to guarantee SQL injection safety
export const SYNCABLE_TABLES = new Set([
  'invoices',
  'invoice_items',
  'sales_returns',
  'sales_return_items',
  'journal_entries',
  'journal_lines',
  'app_settings',
  'items',
  'customers',
  'vendors'
]);

// ----------------------------------------------------------------------------
// 2. DATA TYPES & INTERFACES
// ----------------------------------------------------------------------------

export type SyncAction = 'INSERT' | 'UPDATE' | 'DELETE';

export type SyncStatus = 'IDLE' | 'SYNCING_PUSH' | 'SYNCING_PULL' | 'SUCCESS' | 'ERROR';

export interface SyncRecord {
  table: string;
  id: string;
  action: SyncAction;
  data: Record<string, any>;
}

export interface SyncBatchPayload {
  deviceId: string;
  batchId: string;
  generatedAt: string;
  records: SyncRecord[];
}

export interface DriveBatchFile {
  id: string;
  name: string;
  createdTime: string;
  size?: string;
}

export interface PushResult {
  pushedBatches: number;
  pushedRecords: number;
  batchIds: string[];
}

export interface PullResult {
  pulledBatches: number;
  pulledRecords: number;
  skippedSelfBatches: number;
  latestTimestamp: string | null;
}

export interface SyncResult {
  success: boolean;
  push: PushResult;
  pull: PullResult;
  error?: string;
  durationMs: number;
}

export interface SyncEventDetails {
  status: SyncStatus;
  pushedRecords?: number;
  pulledRecords?: number;
  errorMessage?: string;
  timestamp: string;
}

export type SyncStatusListener = (event: SyncEventDetails) => void;

interface SyncQueueRow {
  queue_id: number;
  entity_table: string;
  record_id: string;
  action_type: SyncAction;
  payload: string | Record<string, any>;
  retry_count: number;
}

// ----------------------------------------------------------------------------
// 3. DOMAIN EXCEPTIONS
// ----------------------------------------------------------------------------

export class SyncException extends Error {
  public readonly code: string;
  constructor(message: string, code: string = 'SYNC_ERROR') {
    super(message);
    this.name = 'SyncException';
    this.code = code;
    Object.setPrototypeOf(this, SyncException.prototype);
  }
}

export class DriveUploadException extends SyncException {
  constructor(message: string) {
    super(message, 'DRIVE_UPLOAD_FAILED');
    this.name = 'DriveUploadException';
    Object.setPrototypeOf(this, DriveUploadException.prototype);
  }
}

export class DriveDownloadException extends SyncException {
  constructor(message: string) {
    super(message, 'DRIVE_DOWNLOAD_FAILED');
    this.name = 'DriveDownloadException';
    Object.setPrototypeOf(this, DriveDownloadException.prototype);
  }
}

export class CorruptedBatchException extends SyncException {
  constructor(message: string) {
    super(message, 'CORRUPTED_BATCH_PAYLOAD');
    this.name = 'CorruptedBatchException';
    Object.setPrototypeOf(this, CorruptedBatchException.prototype);
  }
}

// ----------------------------------------------------------------------------
// 4. LOW-LEVEL DATABASE ADAPTER HELPERS
// ----------------------------------------------------------------------------

function generateUUID(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID().replace(/-/g, '');
  }
  return 'xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

async function queryRows<T = any>(db: SQLiteDatabase, sql: string, params: any[] = []): Promise<T[]> {
  if (typeof db.getAllAsync === 'function') {
    return await db.getAllAsync<T>(sql, ...params);
  }

  if (typeof db.executeSql === 'function') {
    const result = await db.executeSql(sql, params);
    const rowsObj = Array.isArray(result) ? result[0]?.rows : result?.rows;
    if (!rowsObj) return [];

    if (Array.isArray(rowsObj._array)) {
      return rowsObj._array as T[];
    }
    if (typeof rowsObj.raw === 'function') {
      return rowsObj.raw() as T[];
    }
    const output: T[] = [];
    const len = rowsObj.length || 0;
    for (let i = 0; i < len; i++) {
      output.push(rowsObj.item ? rowsObj.item(i) : rowsObj[i]);
    }
    return output;
  }

  throw new Error('Unsupported SQLite Database driver interface.');
}

async function executeStatement(db: SQLiteDatabase, sql: string, params: any[] = []): Promise<any> {
  if (typeof db.runAsync === 'function') {
    return await db.runAsync(sql, ...params);
  }
  if (typeof db.executeSql === 'function') {
    return await db.executeSql(sql, params);
  }
  throw new Error('Unsupported SQLite Database driver interface.');
}

async function runInTransaction<T>(db: SQLiteDatabase, callback: () => Promise<T>): Promise<T> {
  if (typeof db.withTransactionAsync === 'function') {
    return await db.withTransactionAsync(callback);
  }

  await executeStatement(db, 'BEGIN IMMEDIATE TRANSACTION;');
  try {
    const result = await callback();
    await executeStatement(db, 'COMMIT;');
    return result;
  } catch (error) {
    try {
      await executeStatement(db, 'ROLLBACK;');
    } catch {
      // Ignore rollback failure
    }
    throw error;
  }
}

// ----------------------------------------------------------------------------
// 5. BIDIRECTIONAL SYNC ENGINE
// ----------------------------------------------------------------------------

export class SyncEngine {
  private static isSyncRunning = false;
  private static statusListeners: Set<SyncStatusListener> = new Set();
  private static currentStatus: SyncStatus = 'IDLE';

  /**
   * Subscribe to sync status lifecycle events.
   * Returns an unsubscription callback.
   */
  public static onSyncStatusChange(listener: SyncStatusListener): () => void {
    this.statusListeners.add(listener);
    return () => {
      this.statusListeners.delete(listener);
    };
  }

  private static emitStatus(status: SyncStatus, details: Partial<SyncEventDetails> = {}): void {
    this.currentStatus = status;
    const event: SyncEventDetails = {
      status,
      timestamp: new Date().toISOString(),
      ...details,
    };
    for (const listener of this.statusListeners) {
      try {
        listener(event);
      } catch (err) {
        console.error('SyncStatusListener error:', err);
      }
    }
  }

  public static getStatus(): SyncStatus {
    return this.currentStatus;
  }

  // --------------------------------------------------------------------------
  // PUSH PIPELINE
  // --------------------------------------------------------------------------

  /**
   * Push pending outbox records from SQLite `sync_queue` to Google Drive as an append-only JSON batch.
   */
  public static async pushPendingChanges(
    db: SQLiteDatabase,
    accessToken: string,
    options: { deleteAfterSync?: boolean; customBatchSize?: number } = {}
  ): Promise<PushResult> {
    const batchSize = options.customBatchSize || SYNC_CONFIG.BATCH_SIZE;
    const deleteAfterSync = options.deleteAfterSync ?? true;

    const deviceId = (await getSetting(db, SETTINGS_KEYS.DEVICE_ID)) || 'UNKNOWN_DEVICE';
    const folderId = await getSetting(db, SETTINGS_KEYS.GOOGLE_FOLDER_ID);

    if (!folderId) {
      throw new SyncException('Missing google_folder_id in app_settings. Please pair or authenticate first.');
    }

    // 1. Query pending records in FIFO order
    const selectSql = `
      SELECT queue_id, entity_table, record_id, action_type, payload, retry_count
      FROM sync_queue
      WHERE sync_status = 'PENDING'
      ORDER BY queue_id ASC
      LIMIT ?;
    `;
    const pendingRows = await queryRows<SyncQueueRow>(db, selectSql, [batchSize]);

    if (pendingRows.length === 0) {
      return { pushedBatches: 0, pushedRecords: 0, batchIds: [] };
    }

    const queueIds = pendingRows.map((r) => r.queue_id);
    const placeholders = queueIds.map(() => '?').join(', ');

    // 2. Atomically mark items as 'SYNCING'
    const markSyncingSql = `
      UPDATE sync_queue
      SET sync_status = 'SYNCING'
      WHERE queue_id IN (${placeholders});
    `;
    await executeStatement(db, markSyncingSql, queueIds);

    // 3. Compile records and batch payload
    const records: SyncRecord[] = [];
    for (const row of pendingRows) {
      let parsedData: Record<string, any>;
      if (typeof row.payload === 'string') {
        try {
          parsedData = JSON.parse(row.payload);
        } catch {
          parsedData = { raw: row.payload };
        }
      } else {
        parsedData = row.payload;
      }

      records.push({
        table: row.entity_table,
        id: row.record_id,
        action: row.action_type,
        data: parsedData,
      });
    }

    const now = new Date();
    const compactTimestamp = now.toISOString().replace(/[-:T]/g, '').slice(2, 14); // YYMMDDHHMMSS
    const shortUuid = generateUUID().slice(0, 8);
    const batchId = `BATCH-${deviceId}-${compactTimestamp}-${shortUuid}`;
    const fileName = `BATCH_${deviceId}_${now.toISOString().replace(/[:.]/g, '-')}_${generateUUID()}.json`;

    const batchPayload: SyncBatchPayload = {
      deviceId,
      batchId,
      generatedAt: now.toISOString(),
      records,
    };

    // 4. Upload JSON batch to Google Drive via Multipart Upload
    try {
      await this.uploadBatchToDrive(accessToken, folderId, fileName, batchPayload);

      // 5. Success: Clean up or transition status
      if (deleteAfterSync) {
        const deleteSql = `DELETE FROM sync_queue WHERE queue_id IN (${placeholders});`;
        await executeStatement(db, deleteSql, queueIds);
      } else {
        const markSyncedSql = `
          UPDATE sync_queue
          SET sync_status = 'SYNCED', error_message = NULL
          WHERE queue_id IN (${placeholders});
        `;
        await executeStatement(db, markSyncedSql, queueIds);
      }

      return {
        pushedBatches: 1,
        pushedRecords: records.length,
        batchIds: [batchId],
      };
    } catch (uploadError: any) {
      // 6. Error handling: increment retry_count, log error, and reset to 'PENDING' (or 'FAILED')
      const errorMessage = uploadError?.message || String(uploadError);
      const updateErrorSql = `
        UPDATE sync_queue
        SET sync_status = CASE WHEN retry_count + 1 >= ${SYNC_CONFIG.MAX_RETRIES} THEN 'FAILED' ELSE 'PENDING' END,
            retry_count = retry_count + 1,
            error_message = ?
        WHERE queue_id IN (${placeholders});
      `;
      await executeStatement(db, updateErrorSql, [errorMessage, ...queueIds]);
      throw new DriveUploadException(`Failed to push batch ${batchId}: ${errorMessage}`);
    }
  }

  /**
   * Performs multipart REST upload of the batch payload to Google Drive v3.
   */
  private static async uploadBatchToDrive(
    accessToken: string,
    folderId: string,
    fileName: string,
    payload: SyncBatchPayload
  ): Promise<void> {
    const boundary = `-------314159265358979323846_${Date.now()}`;
    const delimiter = `\r\n--${boundary}\r\n`;
    const closeDelimiter = `\r\n--${boundary}--`;

    const metadata = {
      name: fileName,
      parents: [folderId],
      mimeType: 'application/json',
      description: `Accounting sync batch from node ${payload.deviceId} (Count: ${payload.records.length})`,
    };

    const multipartRequestBody =
      delimiter +
      'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
      JSON.stringify(metadata) +
      delimiter +
      'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
      JSON.stringify(payload) +
      closeDelimiter;

    let response: Response;
    try {
      response = await fetch(SYNC_CONFIG.UPLOAD_MULTIPART_URL, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': `multipart/related; boundary=${boundary}`,
        },
        body: multipartRequestBody,
      });
    } catch (networkErr: any) {
      throw new DriveUploadException(`Network connection failed during batch upload: ${networkErr?.message || networkErr}`);
    }

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      throw new DriveUploadException(
        `Google Drive API upload failed with status ${response.status} (${response.statusText}): ${errText}`
      );
    }
  }

  // --------------------------------------------------------------------------
  // PULL PIPELINE
  // --------------------------------------------------------------------------

  /**
   * Pull and apply remote JSON batch changes from Google Drive into local SQLite.
   */
  public static async pullRemoteChanges(
    db: SQLiteDatabase,
    accessToken: string
  ): Promise<PullResult> {
    const currentDeviceId = (await getSetting(db, SETTINGS_KEYS.DEVICE_ID)) || 'UNKNOWN_DEVICE';
    const folderId = await getSetting(db, SETTINGS_KEYS.GOOGLE_FOLDER_ID);

    if (!folderId) {
      throw new SyncException('Missing google_folder_id in app_settings. Device is not paired.');
    }

    // 1. Get high-water mark timestamp from `sync_meta`
    const metaSql = `SELECT last_sync_timestamp FROM sync_meta WHERE entity_name = ? LIMIT 1;`;
    const metaRows = await queryRows<{ last_sync_timestamp: string }>(db, metaSql, [SYNC_CONFIG.GLOBAL_META_ENTITY]);
    const lastSyncTimestamp = metaRows[0]?.last_sync_timestamp || SYNC_CONFIG.DEFAULT_EPOCH_ISO;

    // 2. List remote batch files created after lastSyncTimestamp
    const files = await this.listRemoteBatchFiles(accessToken, folderId, lastSyncTimestamp);

    if (files.length === 0) {
      return {
        pulledBatches: 0,
        pulledRecords: 0,
        skippedSelfBatches: 0,
        latestTimestamp: lastSyncTimestamp,
      };
    }

    let appliedBatchesCount = 0;
    let appliedRecordsCount = 0;
    let skippedSelfCount = 0;
    let latestTimestamp = lastSyncTimestamp;

    // 3. Process each batch sequentially in chronological order
    for (const file of files) {
      const batchPayload = await this.downloadBatchFile(accessToken, file.id);

      // Validate payload schema
      if (!batchPayload || !batchPayload.deviceId || !Array.isArray(batchPayload.records)) {
        console.warn(`[SyncEngine] Skipping corrupted batch file: ${file.name} (${file.id})`);
        continue;
      }

      // Self-Origin Filter: Skip applying batches generated by this local device
      if (batchPayload.deviceId.trim().toUpperCase() === currentDeviceId.trim().toUpperCase()) {
        skippedSelfCount++;
        // Advance high-water mark so we don't re-download our own file next time
        await this.updateHighWaterMark(db, file.createdTime);
        latestTimestamp = file.createdTime;
        continue;
      }

      // 4. Apply batch records in a single transactional unit
      await runInTransaction(db, async () => {
        // Temporarily defer foreign key constraints for bulk synchronization
        await executeStatement(db, 'PRAGMA defer_foreign_keys = ON;');

        // Order records: parents (invoices, sales_returns, journal_entries) before child lines
        const sortedRecords = this.sortRecordsByDependency(batchPayload.records);

        for (const record of sortedRecords) {
          await this.applySyncRecord(db, record);
        }

        // Advance high-water mark to this batch file's createdTime
        await this.updateHighWaterMark(db, file.createdTime);
      });

      appliedBatchesCount++;
      appliedRecordsCount += batchPayload.records.length;
      latestTimestamp = file.createdTime;
    }

    return {
      pulledBatches: appliedBatchesCount,
      pulledRecords: appliedRecordsCount,
      skippedSelfBatches: skippedSelfCount,
      latestTimestamp,
    };
  }

  /**
   * Queries Google Drive for batch files created after the given timestamp.
   */
  private static async listRemoteBatchFiles(
    accessToken: string,
    folderId: string,
    createdAfterIso: string
  ): Promise<DriveBatchFile[]> {
    const escapedFolder = folderId.replace(/'/g, "\\'");
    const query = `'${escapedFolder}' in parents and trashed = false and createdTime > '${createdAfterIso}' and mimeType = 'application/json' and name contains '${SYNC_CONFIG.FILE_PREFIX}'`;

    const url = new URL(SYNC_CONFIG.DRIVE_FILES_URL);
    url.searchParams.append('q', query);
    url.searchParams.append('orderBy', 'createdTime asc');
    url.searchParams.append('fields', 'files(id, name, createdTime, size)');
    url.searchParams.append('pageSize', '100');

    let response: Response;
    try {
      response = await fetch(url.toString(), {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: 'application/json',
        },
      });
    } catch (err: any) {
      throw new DriveDownloadException(`Failed to list remote batch files: ${err?.message || err}`);
    }

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      throw new DriveDownloadException(`Drive listing API returned error ${response.status}: ${errText}`);
    }

    const data = await response.json();
    return (data.files || []) as DriveBatchFile[];
  }

  /**
   * Downloads and parses a JSON batch file from Google Drive.
   */
  private static async downloadBatchFile(
    accessToken: string,
    fileId: string
  ): Promise<SyncBatchPayload> {
    const url = `${SYNC_CONFIG.DRIVE_FILES_URL}/${encodeURIComponent(fileId)}?alt=media`;

    let response: Response;
    try {
      response = await fetch(url, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: 'application/json',
        },
      });
    } catch (err: any) {
      throw new DriveDownloadException(`Failed to fetch file content (${fileId}): ${err?.message || err}`);
    }

    if (!response.ok) {
      throw new DriveDownloadException(`Download file API error ${response.status}: ${response.statusText}`);
    }

    try {
      return (await response.json()) as SyncBatchPayload;
    } catch (jsonErr: any) {
      throw new CorruptedBatchException(`Failed to parse batch JSON from file ${fileId}: ${jsonErr?.message}`);
    }
  }

  /**
   * Sorts batch records so that parent headers are inserted before line-item children.
   */
  private static sortRecordsByDependency(records: SyncRecord[]): SyncRecord[] {
    const priorityMap: Record<string, number> = {
      app_settings: 0,
      invoices: 10,
      sales_returns: 10,
      journal_entries: 10,
      invoice_items: 20,
      sales_return_items: 20,
      journal_lines: 20,
    };

    return [...records].sort((a, b) => {
      const pA = priorityMap[a.table] ?? 50;
      const pB = priorityMap[b.table] ?? 50;
      return pA - pB;
    });
  }

  /**
   * Applies an individual sync record to the local SQLite database.
   * Performs idempotent upserts (`INSERT OR REPLACE`) for inserts/updates.
   */
  private static async applySyncRecord(db: SQLiteDatabase, record: SyncRecord): Promise<void> {
    const tableName = record.table.toLowerCase().trim();

    // Whitelist security check to block SQL injection
    if (!SYNCABLE_TABLES.has(tableName)) {
      console.warn(`[SyncEngine] Blocked sync for unwhitelisted table: '${tableName}'`);
      return;
    }

    if (record.action === 'DELETE') {
      const deleteSql = `DELETE FROM ${tableName} WHERE id = ?;`;
      await executeStatement(db, deleteSql, [record.id]);
      return;
    }

    // Handle INSERT and UPDATE actions via idempotent UPSERT
    const dataObj = record.data || {};
    // Ensure primary key `id` is present
    if (!dataObj.id && record.id) {
      dataObj.id = record.id;
    }

    const columns = Object.keys(dataObj).filter((col) => /^[a-zA-Z0-9_]+$/.test(col));
    if (columns.length === 0) {
      return;
    }

    const placeholders = columns.map(() => '?').join(', ');
    const values = columns.map((col) => dataObj[col]);

    const upsertSql = `
      INSERT OR REPLACE INTO ${tableName} (${columns.join(', ')})
      VALUES (${placeholders});
    `;

    await executeStatement(db, upsertSql, values);
  }

  /**
   * Updates `sync_meta` with the latest processed timestamp.
   */
  private static async updateHighWaterMark(db: SQLiteDatabase, timestamp: string): Promise<void> {
    const sql = `
      INSERT INTO sync_meta (entity_name, last_sync_timestamp, updated_at)
      VALUES (?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
      ON CONFLICT(entity_name) DO UPDATE SET
        last_sync_timestamp = excluded.last_sync_timestamp,
        updated_at = excluded.updated_at;
    `;
    await executeStatement(db, sql, [SYNC_CONFIG.GLOBAL_META_ENTITY, timestamp]);
  }

  // --------------------------------------------------------------------------
  // 3. ORCHESTRATOR & EXECUTION CONTROL
  // --------------------------------------------------------------------------

  /**
   * Manually triggers a full bidirectional sync cycle with non-overlapping lock.
   */
  public static async syncNow(db: SQLiteDatabase): Promise<SyncResult> {
    if (this.isSyncRunning) {
      return {
        success: false,
        push: { pushedBatches: 0, pushedRecords: 0, batchIds: [] },
        pull: { pulledBatches: 0, pulledRecords: 0, skippedSelfBatches: 0, latestTimestamp: null },
        error: 'Sync is already in progress.',
        durationMs: 0,
      };
    }

    this.isSyncRunning = true;
    const startTime = Date.now();

    let pushResult: PushResult = { pushedBatches: 0, pushedRecords: 0, batchIds: [] };
    let pullResult: PullResult = {
      pulledBatches: 0,
      pulledRecords: 0,
      skippedSelfBatches: 0,
      latestTimestamp: null,
    };

    try {
      // 1. Verify and obtain guaranteed valid access token
      const accessToken = await DriveAuthService.getValidAccessToken(db);

      // 2. Execute Push Pipeline
      this.emitStatus('SYNCING_PUSH');
      pushResult = await this.pushPendingChanges(db, accessToken);

      // 3. Execute Pull Pipeline
      this.emitStatus('SYNCING_PULL', { pushedRecords: pushResult.pushedRecords });
      pullResult = await this.pullRemoteChanges(db, accessToken);

      // 4. Emit Success Status
      this.emitStatus('SUCCESS', {
        pushedRecords: pushResult.pushedRecords,
        pulledRecords: pullResult.pulledRecords,
      });

      return {
        success: true,
        push: pushResult,
        pull: pullResult,
        durationMs: Date.now() - startTime,
      };
    } catch (err: any) {
      const errorMessage = err?.message || String(err);
      this.emitStatus('ERROR', { errorMessage });
      return {
        success: false,
        push: pushResult,
        pull: pullResult,
        error: errorMessage,
        durationMs: Date.now() - startTime,
      };
    } finally {
      this.isSyncRunning = false;
      setTimeout(() => {
        if (this.currentStatus !== 'SYNCING_PUSH' && this.currentStatus !== 'SYNCING_PULL') {
          this.emitStatus('IDLE');
        }
      }, 3000);
    }
  }

  /**
   * Starts periodic background synchronization.
   *
   * @param db SQLite database connection
   * @param intervalMs Interval between sync attempts (default: 60,000ms)
   * @returns Unsubscribe / Stop function
   */
  public static startPeriodicSync(
    db: SQLiteDatabase,
    intervalMs: number = SYNC_CONFIG.DEFAULT_SYNC_INTERVAL_MS
  ): () => void {
    // Initial sync trigger
    this.syncNow(db).catch((err) => {
      console.warn('[SyncEngine] Initial periodic sync error:', err?.message || err);
    });

    const timerId = setInterval(() => {
      this.syncNow(db).catch((err) => {
        console.warn('[SyncEngine] Periodic sync background tick error:', err?.message || err);
      });
    }, intervalMs);

    return () => {
      clearInterval(timerId);
    };
  }
}

// ----------------------------------------------------------------------------
// 6. CONVENIENCE FUNCTIONAL EXPORTS
// ----------------------------------------------------------------------------

export async function syncNow(db: SQLiteDatabase): Promise<SyncResult> {
  return await SyncEngine.syncNow(db);
}

export function startPeriodicSync(
  db: SQLiteDatabase,
  intervalMs: number = SYNC_CONFIG.DEFAULT_SYNC_INTERVAL_MS
): () => void {
  return SyncEngine.startPeriodicSync(db, intervalMs);
}

export default SyncEngine;
